### ISSUE TITLE
Reproducing Example: Tumor Paired Variant Calling

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen-vm#140]
Hi, 
I would like to reproduce Tumor paired variant calling for better understanding bcbio. I am trying to operate this task on AWS EC2 machines however I am interfering with problems.

First;
I believe I installed it correctly. I followed [the first](https://github.com/chapmanb/bcbio-nextgen-vm) step and it installed bcbio_vm to my amazon AWS EC2 machine.

1) My first question is, as far I understand tutorial in here [https://bcbio-nextgen.readthedocs.org/en/latest/contents/cloud.html](url) is about running bcbio_vm without login in to virtual machine ( with ssh ). However, I think I should be able to run these commands also by loging in to the server? Please clarify me I am misunderstand.

Second;
2) I attached a Elastic Block Store to my AWS instance therefore I allocated my bam files. I am stating this because in the documentation, it was always referred to bucket. Which one is the right one ? Should I change elastic block store with Bucket?

3)I tried to run the process with the following command. Also I changed the locations of the files to the pwd of their location.

I would prefer working on amazon servers while logged in to the instance. Is this a wrong methodology for working in a such a project? My aim is to setup a pipeline that will call mutations for ~250 samples ( paired timor-normal). I am ready to what it is needed to be done. 

Thank you very much for your help and patience.

Tunc.

My error;
```
[ec2-user@ip-172-31-51-202 work]$ bcbio_vm.py run ../config/cancer-dream-syn3.yaml -n 2
Must specify a `--datadir` or save the default location with `saveconfig`.
Could not run analysis.
```

My config file;
```
# Cancer tumor/normal calling evaluation using synthetic dataset 3
# from the ICGC-TCGA DREAM challenge:
# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: true
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect, freebayes, vardict, varscan]
    indelcaller: false
    ensemble:
      numpass: 2
    variant_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/NGv3.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  analysis: variant2
  description: syn3-normal
  #files: ../input/synthetic.challenge.set3.normal.bam
  files:
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_1.fq.gz
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: true
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect, freebayes, vardict, varscan]
    indelcaller: false
    ensemble:
      numpass: 2
    variant_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/NGv3.bed
    validate: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth.vcf.gz
    validate_regions: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth_regions.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  #   svvalidate:
  #     DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
  #     DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
  #     INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
  #     INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz
    - /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2014-08-13'
fc_name: dream-syn3
upload:
  dir: /home/ec2-user/dendi/bcbio_sampledata/cancer-dream-syn3/final
```

Proof that I think I installed right. 
```
[ec2-user@ip-172-31-51-202 work]$ bcbio_vm.py  -h
usage: bcbio_vm.py [-h] [--datadir DATADIR]
                   {run,install,upgrade,ipython,ipythonprep,template,cwl,aws,elasticluster,graph,clusterk,runfn,devel,saveconfig}
                   ...

Automatic installation for bcbio-nextgen pipelines, with docker.

optional arguments:
  -h, --help            show this help message and exit
  --datadir DATADIR     Directory with genome data and associated files.

[sub-commands]:
  {run,install,upgrade,ipython,ipythonprep,template,cwl,aws,elasticluster,graph,clusterk,runfn,devel,saveconfig}
    run                 Run an automated analysis on the local machine.
    install             Install or upgrade bcbio-nextgen docker container and
                        data.
    upgrade             Install or upgrade bcbio-nextgen docker container and
                        data.
    ipython             Run on a cluster using IPython parallel.
    ipythonprep         Prepare a batch script to run bcbio on a scheduler.
    template            Create a bcbio sample.yaml file from a standard
                        template and inputs
    cwl                 Prepare a common workflow language (CWL) input
    aws                 Automate resources for running bcbio on AWS
    elasticluster       Interface to standard elasticluster commands
    graph               Generate system graphs (CPU/memory/network/disk I/O
                        consumption) from bcbio runs
    clusterk            Run on Amazon web services using Clusterk.
    runfn               Run a specific bcbio-nextgen function with provided
                        arguments
    devel               Utilities to help with develping using bcbion inside
                        of docker
    saveconfig          Save standard configuration variables for current
                        user. Avoids need to specify on the command line in
                        future runs.
```
